[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.4"

[features]
resolution = true
skip-lint = false

[programs.localnet]
raydium_cp_swap = "8Z2EU7EHz2GNdwQwW6EmFxQAA7orGbofeg3aZxbDy7he"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../key/uu.json"

[workspace]
members = ["programs/cp-swap"]

[scripts]
build = "rm -rf target && anchor build && mkdir -p target/deploy && cp ./keys/program/keypair.json ./target/deploy/cp_swap-keypair.json"

build-with-so = "anchor run build && ln -s $HOME/.cargo/target/sbf-solana-solana/release/cp_swap.so $PWD/target/deploy/cp_swap.so"

test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"
